@baseUrl = https://api.github.com

@token = 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
@acceptHeader = application/vnd.github.v3.html+json


GET {{baseUrl}}/user/starred?page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}
If-None-Match: W/"ad6fef65793ab31abcdedad29aea540377ab92e3dd8d0874ab5b77c07a3aa1be"


###
GET {{baseUrl}}/search/repositories
  ?q=flutter
  &page=1
Authorization: bearer {{token}}
Accept: {{acceptHeader}}
###

GET {{baseUrl}}/repos/flutter/flutter/readme
Authorization: bearer {{token}}
Accept: {{acceptHeader}}
###

PUT {{baseUrl}}/user/starred/flutter/flutter
Authorization: bearer {{token}}
Content-Length: 0
Accept: {{acceptHeader}}


###
DELETE {{baseUrl}}/user/starred/flutter/flutter
Authorization: bearer {{token}}
Accept: {{acceptHeader}}

###
GET {{baseUrl}}/user/starred/flutter/flutter
Authorization: bearer {{token}}
Accept: {{acceptHeader}}
